#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "smail"
id = "c7b7ee66368e42cea21c50a23fe700dd"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "35c8f737-3047-4ef1-9916-40559e40143a"
preview_database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
migrations_dir = "app/drizzle"


[vars]
COOKIE_SECRET = "test1234abcd"
DOMAIN = "todopi.com"
PASSWORD = "meiyoumima"